// Sample the kawaii potato's EPS paths into point lists for painting with p5.brush.
const fs = require('fs');
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const inner = fs.readFileSync(process.argv[2] || 'kawaii-inner.svg.txt', 'utf8');
const paths = [...inner.matchAll(/<path fill="(#[0-9a-f]{6})" d="([^"]+)"/g)].map((m) => ({ fill: m[1], d: m[2] }));
(async () => {
  const b = await chromium.launch(); const p = await b.newPage();
  const out = await p.evaluate((paths) => {
    const NS = 'http://www.w3.org/2000/svg', svg = document.createElementNS(NS, 'svg'); document.body.appendChild(svg);
    return paths.map(({ fill, d }) => ({
      fill,
      subs: d.split(/(?=M)/).filter((s) => s.trim()).map((sd) => {
        const el = document.createElementNS(NS, 'path'); el.setAttribute('d', sd); svg.appendChild(el);
        const L = el.getTotalLength(), n = Math.max(10, Math.min(90, Math.round(L / 7))), pts = [];
        for (let i = 0; i < n; i++) { const q = el.getPointAtLength((i / n) * L); pts.push([+q.x.toFixed(1), +q.y.toFixed(1)]); }
        return pts;
      }),
    }));
  }, paths);
  // Name the shapes in EPS order (see eps2svg.cjs output).
  const names = ['armR', 'leafR', 'leafRline', 'armL', 'face', 'ring', 'mouth', 'eyeL', 'eyeR', 'hiR1', 'hiR2', 'hiL1', 'hiL2', 'leafL', 'leafLline', 'dot1', 'dot2', 'at'];
  if (out.length !== names.length) throw new Error('shape count ' + out.length);
  const shapes = Object.fromEntries(out.map((s, i) => [names[i], s]));
  fs.writeFileSync('src/poe-shapes.js', '// Generated by extract.cjs from atpotato-20.eps (kawaii potato). Frame: 504.8 x 407.1.\nconst POE_SHAPES = ' + JSON.stringify(shapes) + ';\n');
  console.log(Object.entries(shapes).map(([k, v]) => `${k}:${v.fill}:${v.subs.map((s) => s.length).join('+')}`).join('  '));
  await b.close();
})();
